version: "3.9"

services:
  app:
    build: .
    container_name: my_app
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      MyNetwork:
        ipv4_address: 172.20.0.17

networks:
  MyNetwork:
    external: true